#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDePPySS.DataLinq
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="PPSS")]
	public partial class PPSSClasses_SQLServerDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAlumno(Alumno instance);
    partial void UpdateAlumno(Alumno instance);
    partial void DeleteAlumno(Alumno instance);
    partial void InsertUsuario(Usuario instance);
    partial void UpdateUsuario(Usuario instance);
    partial void DeleteUsuario(Usuario instance);
    partial void InsertCartaAceptacion(CartaAceptacion instance);
    partial void UpdateCartaAceptacion(CartaAceptacion instance);
    partial void DeleteCartaAceptacion(CartaAceptacion instance);
    partial void InsertEntrega(Entrega instance);
    partial void UpdateEntrega(Entrega instance);
    partial void DeleteEntrega(Entrega instance);
    partial void InsertLicenciatura(Licenciatura instance);
    partial void UpdateLicenciatura(Licenciatura instance);
    partial void DeleteLicenciatura(Licenciatura instance);
    partial void InsertOrganizacion(Organizacion instance);
    partial void UpdateOrganizacion(Organizacion instance);
    partial void DeleteOrganizacion(Organizacion instance);
    partial void InsertReporte(Reporte instance);
    partial void UpdateReporte(Reporte instance);
    partial void DeleteReporte(Reporte instance);
    partial void InsertSolicitud(Solicitud instance);
    partial void UpdateSolicitud(Solicitud instance);
    partial void DeleteSolicitud(Solicitud instance);
    partial void InsertTipoSolicitud(TipoSolicitud instance);
    partial void UpdateTipoSolicitud(TipoSolicitud instance);
    partial void DeleteTipoSolicitud(TipoSolicitud instance);
    partial void InsertTipoUsuario(TipoUsuario instance);
    partial void UpdateTipoUsuario(TipoUsuario instance);
    partial void DeleteTipoUsuario(TipoUsuario instance);
    #endregion
		
		public PPSSClasses_SQLServerDataContext() : 
				base(global::ControlDePPySS.Properties.Settings.Default.PPSSConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public PPSSClasses_SQLServerDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PPSSClasses_SQLServerDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PPSSClasses_SQLServerDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PPSSClasses_SQLServerDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Alumno> Alumnos
		{
			get
			{
				return this.GetTable<Alumno>();
			}
		}
		
		public System.Data.Linq.Table<Usuario> Usuarios
		{
			get
			{
				return this.GetTable<Usuario>();
			}
		}
		
		public System.Data.Linq.Table<CartaAceptacion> CartaAceptacions
		{
			get
			{
				return this.GetTable<CartaAceptacion>();
			}
		}
		
		public System.Data.Linq.Table<Entrega> Entregas
		{
			get
			{
				return this.GetTable<Entrega>();
			}
		}
		
		public System.Data.Linq.Table<Licenciatura> Licenciaturas
		{
			get
			{
				return this.GetTable<Licenciatura>();
			}
		}
		
		public System.Data.Linq.Table<Organizacion> Organizacions
		{
			get
			{
				return this.GetTable<Organizacion>();
			}
		}
		
		public System.Data.Linq.Table<Reporte> Reportes
		{
			get
			{
				return this.GetTable<Reporte>();
			}
		}
		
		public System.Data.Linq.Table<Solicitud> Solicituds
		{
			get
			{
				return this.GetTable<Solicitud>();
			}
		}
		
		public System.Data.Linq.Table<TipoSolicitud> TipoSolicituds
		{
			get
			{
				return this.GetTable<TipoSolicitud>();
			}
		}
		
		public System.Data.Linq.Table<TipoUsuario> TipoUsuarios
		{
			get
			{
				return this.GetTable<TipoUsuario>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Alumno")]
	public partial class Alumno : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _matricula;
		
		private string _nombres;
		
		private string _apellido_paterno;
		
		private string _apellido_materno;
		
		private int _ano_ingreso;
		
		private int _licenciatura_id;
		
		private EntitySet<Solicitud> _Solicituds;
		
		private EntityRef<Licenciatura> _Licenciatura;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmatriculaChanging(string value);
    partial void OnmatriculaChanged();
    partial void OnnombresChanging(string value);
    partial void OnnombresChanged();
    partial void Onapellido_paternoChanging(string value);
    partial void Onapellido_paternoChanged();
    partial void Onapellido_maternoChanging(string value);
    partial void Onapellido_maternoChanged();
    partial void Onano_ingresoChanging(int value);
    partial void Onano_ingresoChanged();
    partial void Onlicenciatura_idChanging(int value);
    partial void Onlicenciatura_idChanged();
    #endregion
		
		public Alumno()
		{
			this._Solicituds = new EntitySet<Solicitud>(new Action<Solicitud>(this.attach_Solicituds), new Action<Solicitud>(this.detach_Solicituds));
			this._Licenciatura = default(EntityRef<Licenciatura>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matricula", DbType="VarChar(9) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string matricula
		{
			get
			{
				return this._matricula;
			}
			set
			{
				if ((this._matricula != value))
				{
					this.OnmatriculaChanging(value);
					this.SendPropertyChanging();
					this._matricula = value;
					this.SendPropertyChanged("matricula");
					this.OnmatriculaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombres", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nombres
		{
			get
			{
				return this._nombres;
			}
			set
			{
				if ((this._nombres != value))
				{
					this.OnnombresChanging(value);
					this.SendPropertyChanging();
					this._nombres = value;
					this.SendPropertyChanged("nombres");
					this.OnnombresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellido_paterno", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string apellido_paterno
		{
			get
			{
				return this._apellido_paterno;
			}
			set
			{
				if ((this._apellido_paterno != value))
				{
					this.Onapellido_paternoChanging(value);
					this.SendPropertyChanging();
					this._apellido_paterno = value;
					this.SendPropertyChanged("apellido_paterno");
					this.Onapellido_paternoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellido_materno", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string apellido_materno
		{
			get
			{
				return this._apellido_materno;
			}
			set
			{
				if ((this._apellido_materno != value))
				{
					this.Onapellido_maternoChanging(value);
					this.SendPropertyChanging();
					this._apellido_materno = value;
					this.SendPropertyChanged("apellido_materno");
					this.Onapellido_maternoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ano_ingreso", DbType="Int NOT NULL")]
		public int ano_ingreso
		{
			get
			{
				return this._ano_ingreso;
			}
			set
			{
				if ((this._ano_ingreso != value))
				{
					this.Onano_ingresoChanging(value);
					this.SendPropertyChanging();
					this._ano_ingreso = value;
					this.SendPropertyChanged("ano_ingreso");
					this.Onano_ingresoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_licenciatura_id", DbType="Int NOT NULL")]
		public int licenciatura_id
		{
			get
			{
				return this._licenciatura_id;
			}
			set
			{
				if ((this._licenciatura_id != value))
				{
					if (this._Licenciatura.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onlicenciatura_idChanging(value);
					this.SendPropertyChanging();
					this._licenciatura_id = value;
					this.SendPropertyChanged("licenciatura_id");
					this.Onlicenciatura_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Alumno_Solicitud", Storage="_Solicituds", ThisKey="matricula", OtherKey="matricula")]
		public EntitySet<Solicitud> Solicituds
		{
			get
			{
				return this._Solicituds;
			}
			set
			{
				this._Solicituds.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Licenciatura_Alumno", Storage="_Licenciatura", ThisKey="licenciatura_id", OtherKey="licenciatura_id", IsForeignKey=true)]
		public Licenciatura Licenciatura
		{
			get
			{
				return this._Licenciatura.Entity;
			}
			set
			{
				Licenciatura previousValue = this._Licenciatura.Entity;
				if (((previousValue != value) 
							|| (this._Licenciatura.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Licenciatura.Entity = null;
						previousValue.Alumnos.Remove(this);
					}
					this._Licenciatura.Entity = value;
					if ((value != null))
					{
						value.Alumnos.Add(this);
						this._licenciatura_id = value.licenciatura_id;
					}
					else
					{
						this._licenciatura_id = default(int);
					}
					this.SendPropertyChanged("Licenciatura");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Solicituds(Solicitud entity)
		{
			this.SendPropertyChanging();
			entity.Alumno = this;
		}
		
		private void detach_Solicituds(Solicitud entity)
		{
			this.SendPropertyChanging();
			entity.Alumno = null;
		}

        public override string ToString()
        {
            return nombres + " " + apellido_paterno + " " + apellido_materno;
        }
    }
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Usuario")]
	public partial class Usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _identificador;
		
		private string _contrasena;
		
		private int _tipo_usuario_id;
		
		private EntityRef<TipoUsuario> _TipoUsuario;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidentificadorChanging(string value);
    partial void OnidentificadorChanged();
    partial void OncontrasenaChanging(string value);
    partial void OncontrasenaChanged();
    partial void Ontipo_usuario_idChanging(int value);
    partial void Ontipo_usuario_idChanged();
    #endregion
		
		public Usuario()
		{
			this._TipoUsuario = default(EntityRef<TipoUsuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_identificador", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string identificador
		{
			get
			{
				return this._identificador;
			}
			set
			{
				if ((this._identificador != value))
				{
					this.OnidentificadorChanging(value);
					this.SendPropertyChanging();
					this._identificador = value;
					this.SendPropertyChanged("identificador");
					this.OnidentificadorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contrasena", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string contrasena
		{
			get
			{
				return this._contrasena;
			}
			set
			{
				if ((this._contrasena != value))
				{
					this.OncontrasenaChanging(value);
					this.SendPropertyChanging();
					this._contrasena = value;
					this.SendPropertyChanged("contrasena");
					this.OncontrasenaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipo_usuario_id", DbType="Int NOT NULL")]
		public int tipo_usuario_id
		{
			get
			{
				return this._tipo_usuario_id;
			}
			set
			{
				if ((this._tipo_usuario_id != value))
				{
					if (this._TipoUsuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ontipo_usuario_idChanging(value);
					this.SendPropertyChanging();
					this._tipo_usuario_id = value;
					this.SendPropertyChanged("tipo_usuario_id");
					this.Ontipo_usuario_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TipoUsuario_Usuario", Storage="_TipoUsuario", ThisKey="tipo_usuario_id", OtherKey="tipo_usuario_id", IsForeignKey=true)]
		public TipoUsuario TipoUsuario
		{
			get
			{
				return this._TipoUsuario.Entity;
			}
			set
			{
				TipoUsuario previousValue = this._TipoUsuario.Entity;
				if (((previousValue != value) 
							|| (this._TipoUsuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TipoUsuario.Entity = null;
						previousValue.Usuarios.Remove(this);
					}
					this._TipoUsuario.Entity = value;
					if ((value != null))
					{
						value.Usuarios.Add(this);
						this._tipo_usuario_id = value.tipo_usuario_id;
					}
					else
					{
						this._tipo_usuario_id = default(int);
					}
					this.SendPropertyChanged("TipoUsuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CartaAceptacion")]
	public partial class CartaAceptacion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _carta_aceptacion_id;
		
		private int _horas_a_liberar;
		
		private System.DateTime _fecha_inicio;
		
		private System.DateTime _fecha_fin;
		
		private bool _lunes;
		
		private bool _martes;
		
		private bool _miercoles;
		
		private bool _jueves;
		
		private bool _viernes;
		
		private bool _sabado;
		
		private bool _domingo;
		
		private string _hora_entrada;
		
		private string _hora_salida;
		
		private int _solicitud_id;
		
		private EntityRef<Solicitud> _Solicitud;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncarta_aceptacion_idChanging(int value);
    partial void Oncarta_aceptacion_idChanged();
    partial void Onhoras_a_liberarChanging(int value);
    partial void Onhoras_a_liberarChanged();
    partial void Onfecha_inicioChanging(System.DateTime value);
    partial void Onfecha_inicioChanged();
    partial void Onfecha_finChanging(System.DateTime value);
    partial void Onfecha_finChanged();
    partial void OnlunesChanging(bool value);
    partial void OnlunesChanged();
    partial void OnmartesChanging(bool value);
    partial void OnmartesChanged();
    partial void OnmiercolesChanging(bool value);
    partial void OnmiercolesChanged();
    partial void OnjuevesChanging(bool value);
    partial void OnjuevesChanged();
    partial void OnviernesChanging(bool value);
    partial void OnviernesChanged();
    partial void OnsabadoChanging(bool value);
    partial void OnsabadoChanged();
    partial void OndomingoChanging(bool value);
    partial void OndomingoChanged();
    partial void Onhora_entradaChanging(string value);
    partial void Onhora_entradaChanged();
    partial void Onhora_salidaChanging(string value);
    partial void Onhora_salidaChanged();
    partial void Onsolicitud_idChanging(int value);
    partial void Onsolicitud_idChanged();
    #endregion
		
		public CartaAceptacion()
		{
			this._Solicitud = default(EntityRef<Solicitud>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_carta_aceptacion_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int carta_aceptacion_id
		{
			get
			{
				return this._carta_aceptacion_id;
			}
			set
			{
				if ((this._carta_aceptacion_id != value))
				{
					this.Oncarta_aceptacion_idChanging(value);
					this.SendPropertyChanging();
					this._carta_aceptacion_id = value;
					this.SendPropertyChanged("carta_aceptacion_id");
					this.Oncarta_aceptacion_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_horas_a_liberar", DbType="Int NOT NULL")]
		public int horas_a_liberar
		{
			get
			{
				return this._horas_a_liberar;
			}
			set
			{
				if ((this._horas_a_liberar != value))
				{
					this.Onhoras_a_liberarChanging(value);
					this.SendPropertyChanging();
					this._horas_a_liberar = value;
					this.SendPropertyChanged("horas_a_liberar");
					this.Onhoras_a_liberarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_inicio", DbType="Date NOT NULL")]
		public System.DateTime fecha_inicio
		{
			get
			{
				return this._fecha_inicio;
			}
			set
			{
				if ((this._fecha_inicio != value))
				{
					this.Onfecha_inicioChanging(value);
					this.SendPropertyChanging();
					this._fecha_inicio = value;
					this.SendPropertyChanged("fecha_inicio");
					this.Onfecha_inicioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_fin", DbType="Date NOT NULL")]
		public System.DateTime fecha_fin
		{
			get
			{
				return this._fecha_fin;
			}
			set
			{
				if ((this._fecha_fin != value))
				{
					this.Onfecha_finChanging(value);
					this.SendPropertyChanging();
					this._fecha_fin = value;
					this.SendPropertyChanged("fecha_fin");
					this.Onfecha_finChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lunes", DbType="Bit NOT NULL")]
		public bool lunes
		{
			get
			{
				return this._lunes;
			}
			set
			{
				if ((this._lunes != value))
				{
					this.OnlunesChanging(value);
					this.SendPropertyChanging();
					this._lunes = value;
					this.SendPropertyChanged("lunes");
					this.OnlunesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_martes", DbType="Bit NOT NULL")]
		public bool martes
		{
			get
			{
				return this._martes;
			}
			set
			{
				if ((this._martes != value))
				{
					this.OnmartesChanging(value);
					this.SendPropertyChanging();
					this._martes = value;
					this.SendPropertyChanged("martes");
					this.OnmartesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_miercoles", DbType="Bit NOT NULL")]
		public bool miercoles
		{
			get
			{
				return this._miercoles;
			}
			set
			{
				if ((this._miercoles != value))
				{
					this.OnmiercolesChanging(value);
					this.SendPropertyChanging();
					this._miercoles = value;
					this.SendPropertyChanged("miercoles");
					this.OnmiercolesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jueves", DbType="Bit NOT NULL")]
		public bool jueves
		{
			get
			{
				return this._jueves;
			}
			set
			{
				if ((this._jueves != value))
				{
					this.OnjuevesChanging(value);
					this.SendPropertyChanging();
					this._jueves = value;
					this.SendPropertyChanged("jueves");
					this.OnjuevesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_viernes", DbType="Bit NOT NULL")]
		public bool viernes
		{
			get
			{
				return this._viernes;
			}
			set
			{
				if ((this._viernes != value))
				{
					this.OnviernesChanging(value);
					this.SendPropertyChanging();
					this._viernes = value;
					this.SendPropertyChanged("viernes");
					this.OnviernesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sabado", DbType="Bit NOT NULL")]
		public bool sabado
		{
			get
			{
				return this._sabado;
			}
			set
			{
				if ((this._sabado != value))
				{
					this.OnsabadoChanging(value);
					this.SendPropertyChanging();
					this._sabado = value;
					this.SendPropertyChanged("sabado");
					this.OnsabadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_domingo", DbType="Bit NOT NULL")]
		public bool domingo
		{
			get
			{
				return this._domingo;
			}
			set
			{
				if ((this._domingo != value))
				{
					this.OndomingoChanging(value);
					this.SendPropertyChanging();
					this._domingo = value;
					this.SendPropertyChanged("domingo");
					this.OndomingoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hora_entrada", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string hora_entrada
		{
			get
			{
				return this._hora_entrada;
			}
			set
			{
				if ((this._hora_entrada != value))
				{
					this.Onhora_entradaChanging(value);
					this.SendPropertyChanging();
					this._hora_entrada = value;
					this.SendPropertyChanged("hora_entrada");
					this.Onhora_entradaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hora_salida", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string hora_salida
		{
			get
			{
				return this._hora_salida;
			}
			set
			{
				if ((this._hora_salida != value))
				{
					this.Onhora_salidaChanging(value);
					this.SendPropertyChanging();
					this._hora_salida = value;
					this.SendPropertyChanged("hora_salida");
					this.Onhora_salidaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_solicitud_id", DbType="Int NOT NULL")]
		public int solicitud_id
		{
			get
			{
				return this._solicitud_id;
			}
			set
			{
				if ((this._solicitud_id != value))
				{
					if (this._Solicitud.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onsolicitud_idChanging(value);
					this.SendPropertyChanging();
					this._solicitud_id = value;
					this.SendPropertyChanged("solicitud_id");
					this.Onsolicitud_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Solicitud_CartaAceptacion", Storage="_Solicitud", ThisKey="solicitud_id", OtherKey="solicitud_id", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Solicitud Solicitud
		{
			get
			{
				return this._Solicitud.Entity;
			}
			set
			{
				Solicitud previousValue = this._Solicitud.Entity;
				if (((previousValue != value) 
							|| (this._Solicitud.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Solicitud.Entity = null;
						previousValue.CartaAceptacions.Remove(this);
					}
					this._Solicitud.Entity = value;
					if ((value != null))
					{
						value.CartaAceptacions.Add(this);
						this._solicitud_id = value.solicitud_id;
					}
					else
					{
						this._solicitud_id = default(int);
					}
					this.SendPropertyChanged("Solicitud");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}

        public override string ToString()
        {
            return Solicitud.ToString();
        }
    }
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Entregas")]
	public partial class Entrega : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _entrega_id;
		
		private bool _solicitud;
		
		private bool _carta_aceptacion;
		
		private bool _ficha_identificacion;
		
		private bool _reportes;
		
		private bool _reporte_final;
		
		private bool _informe_final;
		
		private bool _evaluacion_final;
		
		private bool _carta_liberacion_elemento;
		
		private string _solicitud_comentario;
		
		private string _carta_aceptacion_comentario;
		
		private string _ficha_identificacion_comentario;
		
		private string _reportes_comentario;
		
		private string _reporte_final_comentario;
		
		private string _informe_final_comentario;
		
		private string _evaluacion_final_comentario;
		
		private string _carta_liberacion_comentario;
		
		private int _solicitud_id;
		
		private EntityRef<Solicitud> _Solicitud1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onentrega_idChanging(int value);
    partial void Onentrega_idChanged();
    partial void OnsolicitudChanging(bool value);
    partial void OnsolicitudChanged();
    partial void Oncarta_aceptacionChanging(bool value);
    partial void Oncarta_aceptacionChanged();
    partial void Onficha_identificacionChanging(bool value);
    partial void Onficha_identificacionChanged();
    partial void OnreportesChanging(bool value);
    partial void OnreportesChanged();
    partial void Onreporte_finalChanging(bool value);
    partial void Onreporte_finalChanged();
    partial void Oninforme_finalChanging(bool value);
    partial void Oninforme_finalChanged();
    partial void Onevaluacion_finalChanging(bool value);
    partial void Onevaluacion_finalChanged();
    partial void Oncarta_liberacion_elementoChanging(bool value);
    partial void Oncarta_liberacion_elementoChanged();
    partial void Onsolicitud_comentarioChanging(string value);
    partial void Onsolicitud_comentarioChanged();
    partial void Oncarta_aceptacion_comentarioChanging(string value);
    partial void Oncarta_aceptacion_comentarioChanged();
    partial void Onficha_identificacion_comentarioChanging(string value);
    partial void Onficha_identificacion_comentarioChanged();
    partial void Onreportes_comentarioChanging(string value);
    partial void Onreportes_comentarioChanged();
    partial void Onreporte_final_comentarioChanging(string value);
    partial void Onreporte_final_comentarioChanged();
    partial void Oninforme_final_comentarioChanging(string value);
    partial void Oninforme_final_comentarioChanged();
    partial void Onevaluacion_final_comentarioChanging(string value);
    partial void Onevaluacion_final_comentarioChanged();
    partial void Oncarta_liberacion_comentarioChanging(string value);
    partial void Oncarta_liberacion_comentarioChanged();
    partial void Onsolicitud_idChanging(int value);
    partial void Onsolicitud_idChanged();
    #endregion
		
		public Entrega()
		{
			this._Solicitud1 = default(EntityRef<Solicitud>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_entrega_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int entrega_id
		{
			get
			{
				return this._entrega_id;
			}
			set
			{
				if ((this._entrega_id != value))
				{
					this.Onentrega_idChanging(value);
					this.SendPropertyChanging();
					this._entrega_id = value;
					this.SendPropertyChanged("entrega_id");
					this.Onentrega_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_solicitud", DbType="Bit NOT NULL")]
		public bool solicitud
		{
			get
			{
				return this._solicitud;
			}
			set
			{
				if ((this._solicitud != value))
				{
					this.OnsolicitudChanging(value);
					this.SendPropertyChanging();
					this._solicitud = value;
					this.SendPropertyChanged("solicitud");
					this.OnsolicitudChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_carta_aceptacion", DbType="Bit NOT NULL")]
		public bool carta_aceptacion
		{
			get
			{
				return this._carta_aceptacion;
			}
			set
			{
				if ((this._carta_aceptacion != value))
				{
					this.Oncarta_aceptacionChanging(value);
					this.SendPropertyChanging();
					this._carta_aceptacion = value;
					this.SendPropertyChanged("carta_aceptacion");
					this.Oncarta_aceptacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ficha_identificacion", DbType="Bit NOT NULL")]
		public bool ficha_identificacion
		{
			get
			{
				return this._ficha_identificacion;
			}
			set
			{
				if ((this._ficha_identificacion != value))
				{
					this.Onficha_identificacionChanging(value);
					this.SendPropertyChanging();
					this._ficha_identificacion = value;
					this.SendPropertyChanged("ficha_identificacion");
					this.Onficha_identificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_reportes", DbType="Bit NOT NULL")]
		public bool reportes
		{
			get
			{
				return this._reportes;
			}
			set
			{
				if ((this._reportes != value))
				{
					this.OnreportesChanging(value);
					this.SendPropertyChanging();
					this._reportes = value;
					this.SendPropertyChanged("reportes");
					this.OnreportesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_reporte_final", DbType="Bit NOT NULL")]
		public bool reporte_final
		{
			get
			{
				return this._reporte_final;
			}
			set
			{
				if ((this._reporte_final != value))
				{
					this.Onreporte_finalChanging(value);
					this.SendPropertyChanging();
					this._reporte_final = value;
					this.SendPropertyChanged("reporte_final");
					this.Onreporte_finalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_informe_final", DbType="Bit NOT NULL")]
		public bool informe_final
		{
			get
			{
				return this._informe_final;
			}
			set
			{
				if ((this._informe_final != value))
				{
					this.Oninforme_finalChanging(value);
					this.SendPropertyChanging();
					this._informe_final = value;
					this.SendPropertyChanged("informe_final");
					this.Oninforme_finalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_evaluacion_final", DbType="Bit NOT NULL")]
		public bool evaluacion_final
		{
			get
			{
				return this._evaluacion_final;
			}
			set
			{
				if ((this._evaluacion_final != value))
				{
					this.Onevaluacion_finalChanging(value);
					this.SendPropertyChanging();
					this._evaluacion_final = value;
					this.SendPropertyChanged("evaluacion_final");
					this.Onevaluacion_finalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_carta_liberacion_elemento", DbType="Bit NOT NULL")]
		public bool carta_liberacion_elemento
		{
			get
			{
				return this._carta_liberacion_elemento;
			}
			set
			{
				if ((this._carta_liberacion_elemento != value))
				{
					this.Oncarta_liberacion_elementoChanging(value);
					this.SendPropertyChanging();
					this._carta_liberacion_elemento = value;
					this.SendPropertyChanged("carta_liberacion_elemento");
					this.Oncarta_liberacion_elementoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_solicitud_comentario", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string solicitud_comentario
		{
			get
			{
				return this._solicitud_comentario;
			}
			set
			{
				if ((this._solicitud_comentario != value))
				{
					this.Onsolicitud_comentarioChanging(value);
					this.SendPropertyChanging();
					this._solicitud_comentario = value;
					this.SendPropertyChanged("solicitud_comentario");
					this.Onsolicitud_comentarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_carta_aceptacion_comentario", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string carta_aceptacion_comentario
		{
			get
			{
				return this._carta_aceptacion_comentario;
			}
			set
			{
				if ((this._carta_aceptacion_comentario != value))
				{
					this.Oncarta_aceptacion_comentarioChanging(value);
					this.SendPropertyChanging();
					this._carta_aceptacion_comentario = value;
					this.SendPropertyChanged("carta_aceptacion_comentario");
					this.Oncarta_aceptacion_comentarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ficha_identificacion_comentario", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string ficha_identificacion_comentario
		{
			get
			{
				return this._ficha_identificacion_comentario;
			}
			set
			{
				if ((this._ficha_identificacion_comentario != value))
				{
					this.Onficha_identificacion_comentarioChanging(value);
					this.SendPropertyChanging();
					this._ficha_identificacion_comentario = value;
					this.SendPropertyChanged("ficha_identificacion_comentario");
					this.Onficha_identificacion_comentarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_reportes_comentario", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string reportes_comentario
		{
			get
			{
				return this._reportes_comentario;
			}
			set
			{
				if ((this._reportes_comentario != value))
				{
					this.Onreportes_comentarioChanging(value);
					this.SendPropertyChanging();
					this._reportes_comentario = value;
					this.SendPropertyChanged("reportes_comentario");
					this.Onreportes_comentarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_reporte_final_comentario", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string reporte_final_comentario
		{
			get
			{
				return this._reporte_final_comentario;
			}
			set
			{
				if ((this._reporte_final_comentario != value))
				{
					this.Onreporte_final_comentarioChanging(value);
					this.SendPropertyChanging();
					this._reporte_final_comentario = value;
					this.SendPropertyChanged("reporte_final_comentario");
					this.Onreporte_final_comentarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_informe_final_comentario", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string informe_final_comentario
		{
			get
			{
				return this._informe_final_comentario;
			}
			set
			{
				if ((this._informe_final_comentario != value))
				{
					this.Oninforme_final_comentarioChanging(value);
					this.SendPropertyChanging();
					this._informe_final_comentario = value;
					this.SendPropertyChanged("informe_final_comentario");
					this.Oninforme_final_comentarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_evaluacion_final_comentario", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string evaluacion_final_comentario
		{
			get
			{
				return this._evaluacion_final_comentario;
			}
			set
			{
				if ((this._evaluacion_final_comentario != value))
				{
					this.Onevaluacion_final_comentarioChanging(value);
					this.SendPropertyChanging();
					this._evaluacion_final_comentario = value;
					this.SendPropertyChanged("evaluacion_final_comentario");
					this.Onevaluacion_final_comentarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_carta_liberacion_comentario", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string carta_liberacion_comentario
		{
			get
			{
				return this._carta_liberacion_comentario;
			}
			set
			{
				if ((this._carta_liberacion_comentario != value))
				{
					this.Oncarta_liberacion_comentarioChanging(value);
					this.SendPropertyChanging();
					this._carta_liberacion_comentario = value;
					this.SendPropertyChanged("carta_liberacion_comentario");
					this.Oncarta_liberacion_comentarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_solicitud_id", DbType="Int NOT NULL")]
		public int solicitud_id
		{
			get
			{
				return this._solicitud_id;
			}
			set
			{
				if ((this._solicitud_id != value))
				{
					if (this._Solicitud1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onsolicitud_idChanging(value);
					this.SendPropertyChanging();
					this._solicitud_id = value;
					this.SendPropertyChanged("solicitud_id");
					this.Onsolicitud_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Solicitud_Entrega", Storage="_Solicitud1", ThisKey="solicitud_id", OtherKey="solicitud_id", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Solicitud Solicitud1
		{
			get
			{
				return this._Solicitud1.Entity;
			}
			set
			{
				Solicitud previousValue = this._Solicitud1.Entity;
				if (((previousValue != value) 
							|| (this._Solicitud1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Solicitud1.Entity = null;
						previousValue.Entregas.Remove(this);
					}
					this._Solicitud1.Entity = value;
					if ((value != null))
					{
						value.Entregas.Add(this);
						this._solicitud_id = value.solicitud_id;
					}
					else
					{
						this._solicitud_id = default(int);
					}
					this.SendPropertyChanged("Solicitud1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Licenciatura")]
	public partial class Licenciatura : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _licenciatura_id;
		
		private string _nombre;
		
		private int _duracion;
		
		private EntitySet<Alumno> _Alumnos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onlicenciatura_idChanging(int value);
    partial void Onlicenciatura_idChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OnduracionChanging(int value);
    partial void OnduracionChanged();
    #endregion
		
		public Licenciatura()
		{
			this._Alumnos = new EntitySet<Alumno>(new Action<Alumno>(this.attach_Alumnos), new Action<Alumno>(this.detach_Alumnos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_licenciatura_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int licenciatura_id
		{
			get
			{
				return this._licenciatura_id;
			}
			set
			{
				if ((this._licenciatura_id != value))
				{
					this.Onlicenciatura_idChanging(value);
					this.SendPropertyChanging();
					this._licenciatura_id = value;
					this.SendPropertyChanged("licenciatura_id");
					this.Onlicenciatura_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_duracion", DbType="Int NOT NULL")]
		public int duracion
		{
			get
			{
				return this._duracion;
			}
			set
			{
				if ((this._duracion != value))
				{
					this.OnduracionChanging(value);
					this.SendPropertyChanging();
					this._duracion = value;
					this.SendPropertyChanged("duracion");
					this.OnduracionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Licenciatura_Alumno", Storage="_Alumnos", ThisKey="licenciatura_id", OtherKey="licenciatura_id")]
		public EntitySet<Alumno> Alumnos
		{
			get
			{
				return this._Alumnos;
			}
			set
			{
				this._Alumnos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Alumnos(Alumno entity)
		{
			this.SendPropertyChanging();
			entity.Licenciatura = this;
		}
		
		private void detach_Alumnos(Alumno entity)
		{
			this.SendPropertyChanging();
			entity.Licenciatura = null;
		}

        public override string ToString()
        {
            return nombre;
        }

        public override bool Equals(object obj)
        {
            if (obj.GetType() == typeof(Licenciatura))
            {
                Licenciatura lic = (Licenciatura)obj;

                if (lic.licenciatura_id == licenciatura_id)
                {
                    return true;
                }
            }

            return false;
        }
    }
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Organizacion")]
	public partial class Organizacion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _organizacion_id;
		
		private string _nombre;
		
		private string _direccion;
		
		private EntitySet<Solicitud> _Solicituds;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onorganizacion_idChanging(int value);
    partial void Onorganizacion_idChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OndireccionChanging(string value);
    partial void OndireccionChanged();
    #endregion
		
		public Organizacion()
		{
			this._Solicituds = new EntitySet<Solicitud>(new Action<Solicitud>(this.attach_Solicituds), new Action<Solicitud>(this.detach_Solicituds));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_organizacion_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int organizacion_id
		{
			get
			{
				return this._organizacion_id;
			}
			set
			{
				if ((this._organizacion_id != value))
				{
					this.Onorganizacion_idChanging(value);
					this.SendPropertyChanging();
					this._organizacion_id = value;
					this.SendPropertyChanged("organizacion_id");
					this.Onorganizacion_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccion", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string direccion
		{
			get
			{
				return this._direccion;
			}
			set
			{
				if ((this._direccion != value))
				{
					this.OndireccionChanging(value);
					this.SendPropertyChanging();
					this._direccion = value;
					this.SendPropertyChanged("direccion");
					this.OndireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Organizacion_Solicitud", Storage="_Solicituds", ThisKey="organizacion_id", OtherKey="organizacion_id")]
		public EntitySet<Solicitud> Solicituds
		{
			get
			{
				return this._Solicituds;
			}
			set
			{
				this._Solicituds.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Solicituds(Solicitud entity)
		{
			this.SendPropertyChanging();
			entity.Organizacion = this;
		}
		
		private void detach_Solicituds(Solicitud entity)
		{
			this.SendPropertyChanging();
			entity.Organizacion = null;
		}

        public override string ToString()
        {
            return nombre;
        }
    }
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Reporte")]
	public partial class Reporte : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _reporte_id;
		
		private int _horas_liberadas;
		
		private System.DateTime _fecha_inicio;
		
		private System.DateTime _fecha_fin;
		
		private bool _firma_coordinador;
		
		private int _solicitud_id;
		
		private EntityRef<Solicitud> _Solicitud;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onreporte_idChanging(int value);
    partial void Onreporte_idChanged();
    partial void Onhoras_liberadasChanging(int value);
    partial void Onhoras_liberadasChanged();
    partial void Onfecha_inicioChanging(System.DateTime value);
    partial void Onfecha_inicioChanged();
    partial void Onfecha_finChanging(System.DateTime value);
    partial void Onfecha_finChanged();
    partial void Onfirma_coordinadorChanging(bool value);
    partial void Onfirma_coordinadorChanged();
    partial void Onsolicitud_idChanging(int value);
    partial void Onsolicitud_idChanged();
    #endregion
		
		public Reporte()
		{
			this._Solicitud = default(EntityRef<Solicitud>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_reporte_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int reporte_id
		{
			get
			{
				return this._reporte_id;
			}
			set
			{
				if ((this._reporte_id != value))
				{
					this.Onreporte_idChanging(value);
					this.SendPropertyChanging();
					this._reporte_id = value;
					this.SendPropertyChanged("reporte_id");
					this.Onreporte_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_horas_liberadas", DbType="Int NOT NULL")]
		public int horas_liberadas
		{
			get
			{
				return this._horas_liberadas;
			}
			set
			{
				if ((this._horas_liberadas != value))
				{
					this.Onhoras_liberadasChanging(value);
					this.SendPropertyChanging();
					this._horas_liberadas = value;
					this.SendPropertyChanged("horas_liberadas");
					this.Onhoras_liberadasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_inicio", DbType="Date NOT NULL")]
		public System.DateTime fecha_inicio
		{
			get
			{
				return this._fecha_inicio;
			}
			set
			{
				if ((this._fecha_inicio != value))
				{
					this.Onfecha_inicioChanging(value);
					this.SendPropertyChanging();
					this._fecha_inicio = value;
					this.SendPropertyChanged("fecha_inicio");
					this.Onfecha_inicioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_fin", DbType="Date NOT NULL")]
		public System.DateTime fecha_fin
		{
			get
			{
				return this._fecha_fin;
			}
			set
			{
				if ((this._fecha_fin != value))
				{
					this.Onfecha_finChanging(value);
					this.SendPropertyChanging();
					this._fecha_fin = value;
					this.SendPropertyChanged("fecha_fin");
					this.Onfecha_finChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_firma_coordinador", DbType="Bit NOT NULL")]
		public bool firma_coordinador
		{
			get
			{
				return this._firma_coordinador;
			}
			set
			{
				if ((this._firma_coordinador != value))
				{
					this.Onfirma_coordinadorChanging(value);
					this.SendPropertyChanging();
					this._firma_coordinador = value;
					this.SendPropertyChanged("firma_coordinador");
					this.Onfirma_coordinadorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_solicitud_id", DbType="Int NOT NULL")]
		public int solicitud_id
		{
			get
			{
				return this._solicitud_id;
			}
			set
			{
				if ((this._solicitud_id != value))
				{
					if (this._Solicitud.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onsolicitud_idChanging(value);
					this.SendPropertyChanging();
					this._solicitud_id = value;
					this.SendPropertyChanged("solicitud_id");
					this.Onsolicitud_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Solicitud_Reporte", Storage="_Solicitud", ThisKey="solicitud_id", OtherKey="solicitud_id", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Solicitud Solicitud
		{
			get
			{
				return this._Solicitud.Entity;
			}
			set
			{
				Solicitud previousValue = this._Solicitud.Entity;
				if (((previousValue != value) 
							|| (this._Solicitud.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Solicitud.Entity = null;
						previousValue.Reportes.Remove(this);
					}
					this._Solicitud.Entity = value;
					if ((value != null))
					{
						value.Reportes.Add(this);
						this._solicitud_id = value.solicitud_id;
					}
					else
					{
						this._solicitud_id = default(int);
					}
					this.SendPropertyChanged("Solicitud");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Solicitud")]
	public partial class Solicitud : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _solicitud_id;
		
		private string _jefe_inmediato;
		
		private string _numero_de_contacto;
		
		private string _area;
		
		private bool _en_revision;
		
		private bool _aprobada;
		
		private bool _rechazada;
		
		private bool _cancelada;
		
		private string _matricula;
		
		private int _organizacion_id;
		
		private int _tipo_solicitud_id;
		
		private EntitySet<CartaAceptacion> _CartaAceptacions;
		
		private EntitySet<Entrega> _Entregas;
		
		private EntitySet<Reporte> _Reportes;
		
		private EntityRef<Alumno> _Alumno;
		
		private EntityRef<Organizacion> _Organizacion;
		
		private EntityRef<TipoSolicitud> _TipoSolicitud;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onsolicitud_idChanging(int value);
    partial void Onsolicitud_idChanged();
    partial void Onjefe_inmediatoChanging(string value);
    partial void Onjefe_inmediatoChanged();
    partial void Onnumero_de_contactoChanging(string value);
    partial void Onnumero_de_contactoChanged();
    partial void OnareaChanging(string value);
    partial void OnareaChanged();
    partial void Onen_revisionChanging(bool value);
    partial void Onen_revisionChanged();
    partial void OnaprobadaChanging(bool value);
    partial void OnaprobadaChanged();
    partial void OnrechazadaChanging(bool value);
    partial void OnrechazadaChanged();
    partial void OncanceladaChanging(bool value);
    partial void OncanceladaChanged();
    partial void OnmatriculaChanging(string value);
    partial void OnmatriculaChanged();
    partial void Onorganizacion_idChanging(int value);
    partial void Onorganizacion_idChanged();
    partial void Ontipo_solicitud_idChanging(int value);
    partial void Ontipo_solicitud_idChanged();
    #endregion
		
		public Solicitud()
		{
			this._CartaAceptacions = new EntitySet<CartaAceptacion>(new Action<CartaAceptacion>(this.attach_CartaAceptacions), new Action<CartaAceptacion>(this.detach_CartaAceptacions));
			this._Entregas = new EntitySet<Entrega>(new Action<Entrega>(this.attach_Entregas), new Action<Entrega>(this.detach_Entregas));
			this._Reportes = new EntitySet<Reporte>(new Action<Reporte>(this.attach_Reportes), new Action<Reporte>(this.detach_Reportes));
			this._Alumno = default(EntityRef<Alumno>);
			this._Organizacion = default(EntityRef<Organizacion>);
			this._TipoSolicitud = default(EntityRef<TipoSolicitud>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_solicitud_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int solicitud_id
		{
			get
			{
				return this._solicitud_id;
			}
			set
			{
				if ((this._solicitud_id != value))
				{
					this.Onsolicitud_idChanging(value);
					this.SendPropertyChanging();
					this._solicitud_id = value;
					this.SendPropertyChanged("solicitud_id");
					this.Onsolicitud_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jefe_inmediato", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string jefe_inmediato
		{
			get
			{
				return this._jefe_inmediato;
			}
			set
			{
				if ((this._jefe_inmediato != value))
				{
					this.Onjefe_inmediatoChanging(value);
					this.SendPropertyChanging();
					this._jefe_inmediato = value;
					this.SendPropertyChanged("jefe_inmediato");
					this.Onjefe_inmediatoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numero_de_contacto", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string numero_de_contacto
		{
			get
			{
				return this._numero_de_contacto;
			}
			set
			{
				if ((this._numero_de_contacto != value))
				{
					this.Onnumero_de_contactoChanging(value);
					this.SendPropertyChanging();
					this._numero_de_contacto = value;
					this.SendPropertyChanged("numero_de_contacto");
					this.Onnumero_de_contactoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_area", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string area
		{
			get
			{
				return this._area;
			}
			set
			{
				if ((this._area != value))
				{
					this.OnareaChanging(value);
					this.SendPropertyChanging();
					this._area = value;
					this.SendPropertyChanged("area");
					this.OnareaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_en_revision", DbType="Bit NOT NULL")]
		public bool en_revision
		{
			get
			{
				return this._en_revision;
			}
			set
			{
				if ((this._en_revision != value))
				{
					this.Onen_revisionChanging(value);
					this.SendPropertyChanging();
					this._en_revision = value;
					this.SendPropertyChanged("en_revision");
					this.Onen_revisionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aprobada", DbType="Bit NOT NULL")]
		public bool aprobada
		{
			get
			{
				return this._aprobada;
			}
			set
			{
				if ((this._aprobada != value))
				{
					this.OnaprobadaChanging(value);
					this.SendPropertyChanging();
					this._aprobada = value;
					this.SendPropertyChanged("aprobada");
					this.OnaprobadaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rechazada", DbType="Bit NOT NULL")]
		public bool rechazada
		{
			get
			{
				return this._rechazada;
			}
			set
			{
				if ((this._rechazada != value))
				{
					this.OnrechazadaChanging(value);
					this.SendPropertyChanging();
					this._rechazada = value;
					this.SendPropertyChanged("rechazada");
					this.OnrechazadaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cancelada", DbType="Bit NOT NULL")]
		public bool cancelada
		{
			get
			{
				return this._cancelada;
			}
			set
			{
				if ((this._cancelada != value))
				{
					this.OncanceladaChanging(value);
					this.SendPropertyChanging();
					this._cancelada = value;
					this.SendPropertyChanged("cancelada");
					this.OncanceladaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matricula", DbType="VarChar(9) NOT NULL", CanBeNull=false)]
		public string matricula
		{
			get
			{
				return this._matricula;
			}
			set
			{
				if ((this._matricula != value))
				{
					if (this._Alumno.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmatriculaChanging(value);
					this.SendPropertyChanging();
					this._matricula = value;
					this.SendPropertyChanged("matricula");
					this.OnmatriculaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_organizacion_id", DbType="Int NOT NULL")]
		public int organizacion_id
		{
			get
			{
				return this._organizacion_id;
			}
			set
			{
				if ((this._organizacion_id != value))
				{
					if (this._Organizacion.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onorganizacion_idChanging(value);
					this.SendPropertyChanging();
					this._organizacion_id = value;
					this.SendPropertyChanged("organizacion_id");
					this.Onorganizacion_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipo_solicitud_id", DbType="Int NOT NULL")]
		public int tipo_solicitud_id
		{
			get
			{
				return this._tipo_solicitud_id;
			}
			set
			{
				if ((this._tipo_solicitud_id != value))
				{
					if (this._TipoSolicitud.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ontipo_solicitud_idChanging(value);
					this.SendPropertyChanging();
					this._tipo_solicitud_id = value;
					this.SendPropertyChanged("tipo_solicitud_id");
					this.Ontipo_solicitud_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Solicitud_CartaAceptacion", Storage="_CartaAceptacions", ThisKey="solicitud_id", OtherKey="solicitud_id")]
		public EntitySet<CartaAceptacion> CartaAceptacions
		{
			get
			{
				return this._CartaAceptacions;
			}
			set
			{
				this._CartaAceptacions.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Solicitud_Entrega", Storage="_Entregas", ThisKey="solicitud_id", OtherKey="solicitud_id")]
		public EntitySet<Entrega> Entregas
		{
			get
			{
				return this._Entregas;
			}
			set
			{
				this._Entregas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Solicitud_Reporte", Storage="_Reportes", ThisKey="solicitud_id", OtherKey="solicitud_id")]
		public EntitySet<Reporte> Reportes
		{
			get
			{
				return this._Reportes;
			}
			set
			{
				this._Reportes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Alumno_Solicitud", Storage="_Alumno", ThisKey="matricula", OtherKey="matricula", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Alumno Alumno
		{
			get
			{
				return this._Alumno.Entity;
			}
			set
			{
				Alumno previousValue = this._Alumno.Entity;
				if (((previousValue != value) 
							|| (this._Alumno.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Alumno.Entity = null;
						previousValue.Solicituds.Remove(this);
					}
					this._Alumno.Entity = value;
					if ((value != null))
					{
						value.Solicituds.Add(this);
						this._matricula = value.matricula;
					}
					else
					{
						this._matricula = default(string);
					}
					this.SendPropertyChanged("Alumno");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Organizacion_Solicitud", Storage="_Organizacion", ThisKey="organizacion_id", OtherKey="organizacion_id", IsForeignKey=true)]
		public Organizacion Organizacion
		{
			get
			{
				return this._Organizacion.Entity;
			}
			set
			{
				Organizacion previousValue = this._Organizacion.Entity;
				if (((previousValue != value) 
							|| (this._Organizacion.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Organizacion.Entity = null;
						previousValue.Solicituds.Remove(this);
					}
					this._Organizacion.Entity = value;
					if ((value != null))
					{
						value.Solicituds.Add(this);
						this._organizacion_id = value.organizacion_id;
					}
					else
					{
						this._organizacion_id = default(int);
					}
					this.SendPropertyChanged("Organizacion");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TipoSolicitud_Solicitud", Storage="_TipoSolicitud", ThisKey="tipo_solicitud_id", OtherKey="tipo_solicitud_id", IsForeignKey=true)]
		public TipoSolicitud TipoSolicitud
		{
			get
			{
				return this._TipoSolicitud.Entity;
			}
			set
			{
				TipoSolicitud previousValue = this._TipoSolicitud.Entity;
				if (((previousValue != value) 
							|| (this._TipoSolicitud.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TipoSolicitud.Entity = null;
						previousValue.Solicituds.Remove(this);
					}
					this._TipoSolicitud.Entity = value;
					if ((value != null))
					{
						value.Solicituds.Add(this);
						this._tipo_solicitud_id = value.tipo_solicitud_id;
					}
					else
					{
						this._tipo_solicitud_id = default(int);
					}
					this.SendPropertyChanged("TipoSolicitud");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CartaAceptacions(CartaAceptacion entity)
		{
			this.SendPropertyChanging();
			entity.Solicitud = this;
		}
		
		private void detach_CartaAceptacions(CartaAceptacion entity)
		{
			this.SendPropertyChanging();
			entity.Solicitud = null;
		}
		
		private void attach_Entregas(Entrega entity)
		{
			this.SendPropertyChanging();
			entity.Solicitud1 = this;
		}
		
		private void detach_Entregas(Entrega entity)
		{
			this.SendPropertyChanging();
			entity.Solicitud1 = null;
		}
		
		private void attach_Reportes(Reporte entity)
		{
			this.SendPropertyChanging();
			entity.Solicitud = this;
		}
		
		private void detach_Reportes(Reporte entity)
		{
			this.SendPropertyChanging();
			entity.Solicitud = null;
		}

        public override string ToString()
        {
            return Organizacion.ToString() + " (" + TipoSolicitud.ToString() + ")";
        }
    }
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TipoSolicitud")]
	public partial class TipoSolicitud : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _tipo_solicitud_id;
		
		private string _nombre;
		
		private EntitySet<Solicitud> _Solicituds;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ontipo_solicitud_idChanging(int value);
    partial void Ontipo_solicitud_idChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    #endregion
		
		public TipoSolicitud()
		{
			this._Solicituds = new EntitySet<Solicitud>(new Action<Solicitud>(this.attach_Solicituds), new Action<Solicitud>(this.detach_Solicituds));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipo_solicitud_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int tipo_solicitud_id
		{
			get
			{
				return this._tipo_solicitud_id;
			}
			set
			{
				if ((this._tipo_solicitud_id != value))
				{
					this.Ontipo_solicitud_idChanging(value);
					this.SendPropertyChanging();
					this._tipo_solicitud_id = value;
					this.SendPropertyChanged("tipo_solicitud_id");
					this.Ontipo_solicitud_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TipoSolicitud_Solicitud", Storage="_Solicituds", ThisKey="tipo_solicitud_id", OtherKey="tipo_solicitud_id")]
		public EntitySet<Solicitud> Solicituds
		{
			get
			{
				return this._Solicituds;
			}
			set
			{
				this._Solicituds.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Solicituds(Solicitud entity)
		{
			this.SendPropertyChanging();
			entity.TipoSolicitud = this;
		}
		
		private void detach_Solicituds(Solicitud entity)
		{
			this.SendPropertyChanging();
			entity.TipoSolicitud = null;
		}

        public override string ToString()
        {
            return nombre;
        }
    }
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TipoUsuario")]
	public partial class TipoUsuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _tipo_usuario_id;
		
		private string _nombre;
		
		private EntitySet<Usuario> _Usuarios;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ontipo_usuario_idChanging(int value);
    partial void Ontipo_usuario_idChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    #endregion
		
		public TipoUsuario()
		{
			this._Usuarios = new EntitySet<Usuario>(new Action<Usuario>(this.attach_Usuarios), new Action<Usuario>(this.detach_Usuarios));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipo_usuario_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int tipo_usuario_id
		{
			get
			{
				return this._tipo_usuario_id;
			}
			set
			{
				if ((this._tipo_usuario_id != value))
				{
					this.Ontipo_usuario_idChanging(value);
					this.SendPropertyChanging();
					this._tipo_usuario_id = value;
					this.SendPropertyChanged("tipo_usuario_id");
					this.Ontipo_usuario_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TipoUsuario_Usuario", Storage="_Usuarios", ThisKey="tipo_usuario_id", OtherKey="tipo_usuario_id")]
		public EntitySet<Usuario> Usuarios
		{
			get
			{
				return this._Usuarios;
			}
			set
			{
				this._Usuarios.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Usuarios(Usuario entity)
		{
			this.SendPropertyChanging();
			entity.TipoUsuario = this;
		}
		
		private void detach_Usuarios(Usuario entity)
		{
			this.SendPropertyChanging();
			entity.TipoUsuario = null;
		}


	}
}
#pragma warning restore 1591
