#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDePPySS
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="sistemaBibliotecario")]
	public partial class ClasesEjemploDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertArea(Area instance);
    partial void UpdateArea(Area instance);
    partial void DeleteArea(Area instance);
    partial void InsertUsuario(Usuario instance);
    partial void UpdateUsuario(Usuario instance);
    partial void DeleteUsuario(Usuario instance);
    partial void InsertDetallePrestamo(DetallePrestamo instance);
    partial void UpdateDetallePrestamo(DetallePrestamo instance);
    partial void DeleteDetallePrestamo(DetallePrestamo instance);
    partial void InsertLibro(Libro instance);
    partial void UpdateLibro(Libro instance);
    partial void DeleteLibro(Libro instance);
    partial void InsertPrestamo(Prestamo instance);
    partial void UpdatePrestamo(Prestamo instance);
    partial void DeletePrestamo(Prestamo instance);
    partial void InsertSancione(Sancione instance);
    partial void UpdateSancione(Sancione instance);
    partial void DeleteSancione(Sancione instance);
    #endregion
		
		public ClasesEjemploDataContext() : 
				base(global::ControlDePPySS.Properties.Settings.Default.sistemaBibliotecarioConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ClasesEjemploDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ClasesEjemploDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ClasesEjemploDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ClasesEjemploDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Area> Areas
		{
			get
			{
				return this.GetTable<Area>();
			}
		}
		
		public System.Data.Linq.Table<Usuario> Usuarios
		{
			get
			{
				return this.GetTable<Usuario>();
			}
		}
		
		public System.Data.Linq.Table<DetallePrestamo> DetallePrestamos
		{
			get
			{
				return this.GetTable<DetallePrestamo>();
			}
		}
		
		public System.Data.Linq.Table<Libro> Libros
		{
			get
			{
				return this.GetTable<Libro>();
			}
		}
		
		public System.Data.Linq.Table<Prestamo> Prestamos
		{
			get
			{
				return this.GetTable<Prestamo>();
			}
		}
		
		public System.Data.Linq.Table<Sancione> Sanciones
		{
			get
			{
				return this.GetTable<Sancione>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Areas")]
	public partial class Area : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _areCodigo;
		
		private string _areNombre;
		
		private int _areTiempo;
		
		private EntitySet<Libro> _Libros;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnareCodigoChanging(int value);
    partial void OnareCodigoChanged();
    partial void OnareNombreChanging(string value);
    partial void OnareNombreChanged();
    partial void OnareTiempoChanging(int value);
    partial void OnareTiempoChanged();
    #endregion
		
		public Area()
		{
			this._Libros = new EntitySet<Libro>(new Action<Libro>(this.attach_Libros), new Action<Libro>(this.detach_Libros));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_areCodigo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int areCodigo
		{
			get
			{
				return this._areCodigo;
			}
			set
			{
				if ((this._areCodigo != value))
				{
					this.OnareCodigoChanging(value);
					this.SendPropertyChanging();
					this._areCodigo = value;
					this.SendPropertyChanged("areCodigo");
					this.OnareCodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_areNombre", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string areNombre
		{
			get
			{
				return this._areNombre;
			}
			set
			{
				if ((this._areNombre != value))
				{
					this.OnareNombreChanging(value);
					this.SendPropertyChanging();
					this._areNombre = value;
					this.SendPropertyChanged("areNombre");
					this.OnareNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_areTiempo", DbType="Int NOT NULL")]
		public int areTiempo
		{
			get
			{
				return this._areTiempo;
			}
			set
			{
				if ((this._areTiempo != value))
				{
					this.OnareTiempoChanging(value);
					this.SendPropertyChanging();
					this._areTiempo = value;
					this.SendPropertyChanged("areTiempo");
					this.OnareTiempoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Area_Libro", Storage="_Libros", ThisKey="areCodigo", OtherKey="areCodigo")]
		public EntitySet<Libro> Libros
		{
			get
			{
				return this._Libros;
			}
			set
			{
				this._Libros.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Libros(Libro entity)
		{
			this.SendPropertyChanging();
			entity.Area = this;
		}
		
		private void detach_Libros(Libro entity)
		{
			this.SendPropertyChanging();
			entity.Area = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Usuarios")]
	public partial class Usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _usuDocumento;
		
		private string _usuNombre;
		
		private string _usuDireccion;
		
		private string _usuTelefono;
		
		private string _usuCorreo;
		
		private string _usuEstado;
		
		private EntitySet<Prestamo> _Prestamos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnusuDocumentoChanging(int value);
    partial void OnusuDocumentoChanged();
    partial void OnusuNombreChanging(string value);
    partial void OnusuNombreChanged();
    partial void OnusuDireccionChanging(string value);
    partial void OnusuDireccionChanged();
    partial void OnusuTelefonoChanging(string value);
    partial void OnusuTelefonoChanged();
    partial void OnusuCorreoChanging(string value);
    partial void OnusuCorreoChanged();
    partial void OnusuEstadoChanging(string value);
    partial void OnusuEstadoChanged();
    #endregion
		
		public Usuario()
		{
			this._Prestamos = new EntitySet<Prestamo>(new Action<Prestamo>(this.attach_Prestamos), new Action<Prestamo>(this.detach_Prestamos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuDocumento", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int usuDocumento
		{
			get
			{
				return this._usuDocumento;
			}
			set
			{
				if ((this._usuDocumento != value))
				{
					this.OnusuDocumentoChanging(value);
					this.SendPropertyChanging();
					this._usuDocumento = value;
					this.SendPropertyChanged("usuDocumento");
					this.OnusuDocumentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuNombre", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string usuNombre
		{
			get
			{
				return this._usuNombre;
			}
			set
			{
				if ((this._usuNombre != value))
				{
					this.OnusuNombreChanging(value);
					this.SendPropertyChanging();
					this._usuNombre = value;
					this.SendPropertyChanged("usuNombre");
					this.OnusuNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuDireccion", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string usuDireccion
		{
			get
			{
				return this._usuDireccion;
			}
			set
			{
				if ((this._usuDireccion != value))
				{
					this.OnusuDireccionChanging(value);
					this.SendPropertyChanging();
					this._usuDireccion = value;
					this.SendPropertyChanged("usuDireccion");
					this.OnusuDireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuTelefono", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string usuTelefono
		{
			get
			{
				return this._usuTelefono;
			}
			set
			{
				if ((this._usuTelefono != value))
				{
					this.OnusuTelefonoChanging(value);
					this.SendPropertyChanging();
					this._usuTelefono = value;
					this.SendPropertyChanged("usuTelefono");
					this.OnusuTelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuCorreo", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string usuCorreo
		{
			get
			{
				return this._usuCorreo;
			}
			set
			{
				if ((this._usuCorreo != value))
				{
					this.OnusuCorreoChanging(value);
					this.SendPropertyChanging();
					this._usuCorreo = value;
					this.SendPropertyChanged("usuCorreo");
					this.OnusuCorreoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuEstado", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string usuEstado
		{
			get
			{
				return this._usuEstado;
			}
			set
			{
				if ((this._usuEstado != value))
				{
					this.OnusuEstadoChanging(value);
					this.SendPropertyChanging();
					this._usuEstado = value;
					this.SendPropertyChanged("usuEstado");
					this.OnusuEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_Prestamo", Storage="_Prestamos", ThisKey="usuDocumento", OtherKey="usuDocumento")]
		public EntitySet<Prestamo> Prestamos
		{
			get
			{
				return this._Prestamos;
			}
			set
			{
				this._Prestamos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Prestamos(Prestamo entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = this;
		}
		
		private void detach_Prestamos(Prestamo entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DetallePrestamos")]
	public partial class DetallePrestamo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _dtpCodigo;
		
		private int _dtpCantidad;
		
		private System.DateTime _dtpFechaFin;
		
		private System.Nullable<System.DateTime> _dtpFechaDev;
		
		private int _preCodigo;
		
		private int _libCodigo;
		
		private EntityRef<Libro> _Libro;
		
		private EntityRef<Prestamo> _Prestamo;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OndtpCodigoChanging(int value);
    partial void OndtpCodigoChanged();
    partial void OndtpCantidadChanging(int value);
    partial void OndtpCantidadChanged();
    partial void OndtpFechaFinChanging(System.DateTime value);
    partial void OndtpFechaFinChanged();
    partial void OndtpFechaDevChanging(System.Nullable<System.DateTime> value);
    partial void OndtpFechaDevChanged();
    partial void OnpreCodigoChanging(int value);
    partial void OnpreCodigoChanged();
    partial void OnlibCodigoChanging(int value);
    partial void OnlibCodigoChanged();
    #endregion
		
		public DetallePrestamo()
		{
			this._Libro = default(EntityRef<Libro>);
			this._Prestamo = default(EntityRef<Prestamo>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dtpCodigo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int dtpCodigo
		{
			get
			{
				return this._dtpCodigo;
			}
			set
			{
				if ((this._dtpCodigo != value))
				{
					this.OndtpCodigoChanging(value);
					this.SendPropertyChanging();
					this._dtpCodigo = value;
					this.SendPropertyChanged("dtpCodigo");
					this.OndtpCodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dtpCantidad", DbType="Int NOT NULL")]
		public int dtpCantidad
		{
			get
			{
				return this._dtpCantidad;
			}
			set
			{
				if ((this._dtpCantidad != value))
				{
					this.OndtpCantidadChanging(value);
					this.SendPropertyChanging();
					this._dtpCantidad = value;
					this.SendPropertyChanged("dtpCantidad");
					this.OndtpCantidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dtpFechaFin", DbType="Date NOT NULL")]
		public System.DateTime dtpFechaFin
		{
			get
			{
				return this._dtpFechaFin;
			}
			set
			{
				if ((this._dtpFechaFin != value))
				{
					this.OndtpFechaFinChanging(value);
					this.SendPropertyChanging();
					this._dtpFechaFin = value;
					this.SendPropertyChanged("dtpFechaFin");
					this.OndtpFechaFinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dtpFechaDev", DbType="Date")]
		public System.Nullable<System.DateTime> dtpFechaDev
		{
			get
			{
				return this._dtpFechaDev;
			}
			set
			{
				if ((this._dtpFechaDev != value))
				{
					this.OndtpFechaDevChanging(value);
					this.SendPropertyChanging();
					this._dtpFechaDev = value;
					this.SendPropertyChanged("dtpFechaDev");
					this.OndtpFechaDevChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_preCodigo", DbType="Int NOT NULL")]
		public int preCodigo
		{
			get
			{
				return this._preCodigo;
			}
			set
			{
				if ((this._preCodigo != value))
				{
					if (this._Prestamo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnpreCodigoChanging(value);
					this.SendPropertyChanging();
					this._preCodigo = value;
					this.SendPropertyChanged("preCodigo");
					this.OnpreCodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_libCodigo", DbType="Int NOT NULL")]
		public int libCodigo
		{
			get
			{
				return this._libCodigo;
			}
			set
			{
				if ((this._libCodigo != value))
				{
					if (this._Libro.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnlibCodigoChanging(value);
					this.SendPropertyChanging();
					this._libCodigo = value;
					this.SendPropertyChanged("libCodigo");
					this.OnlibCodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Libro_DetallePrestamo", Storage="_Libro", ThisKey="libCodigo", OtherKey="libCodigo", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Libro Libro
		{
			get
			{
				return this._Libro.Entity;
			}
			set
			{
				Libro previousValue = this._Libro.Entity;
				if (((previousValue != value) 
							|| (this._Libro.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Libro.Entity = null;
						previousValue.DetallePrestamos.Remove(this);
					}
					this._Libro.Entity = value;
					if ((value != null))
					{
						value.DetallePrestamos.Add(this);
						this._libCodigo = value.libCodigo;
					}
					else
					{
						this._libCodigo = default(int);
					}
					this.SendPropertyChanged("Libro");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Prestamo_DetallePrestamo", Storage="_Prestamo", ThisKey="preCodigo", OtherKey="preCodigo", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Prestamo Prestamo
		{
			get
			{
				return this._Prestamo.Entity;
			}
			set
			{
				Prestamo previousValue = this._Prestamo.Entity;
				if (((previousValue != value) 
							|| (this._Prestamo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Prestamo.Entity = null;
						previousValue.DetallePrestamos.Remove(this);
					}
					this._Prestamo.Entity = value;
					if ((value != null))
					{
						value.DetallePrestamos.Add(this);
						this._preCodigo = value.preCodigo;
					}
					else
					{
						this._preCodigo = default(int);
					}
					this.SendPropertyChanged("Prestamo");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Libros")]
	public partial class Libro : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _libCodigo;
		
		private string _libNombre;
		
		private int _libNumPag;
		
		private string _libAutor;
		
		private string _libEditorial;
		
		private int _areCodigo;
		
		private EntitySet<DetallePrestamo> _DetallePrestamos;
		
		private EntityRef<Area> _Area;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnlibCodigoChanging(int value);
    partial void OnlibCodigoChanged();
    partial void OnlibNombreChanging(string value);
    partial void OnlibNombreChanged();
    partial void OnlibNumPagChanging(int value);
    partial void OnlibNumPagChanged();
    partial void OnlibAutorChanging(string value);
    partial void OnlibAutorChanged();
    partial void OnlibEditorialChanging(string value);
    partial void OnlibEditorialChanged();
    partial void OnareCodigoChanging(int value);
    partial void OnareCodigoChanged();
    #endregion
		
		public Libro()
		{
			this._DetallePrestamos = new EntitySet<DetallePrestamo>(new Action<DetallePrestamo>(this.attach_DetallePrestamos), new Action<DetallePrestamo>(this.detach_DetallePrestamos));
			this._Area = default(EntityRef<Area>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_libCodigo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int libCodigo
		{
			get
			{
				return this._libCodigo;
			}
			set
			{
				if ((this._libCodigo != value))
				{
					this.OnlibCodigoChanging(value);
					this.SendPropertyChanging();
					this._libCodigo = value;
					this.SendPropertyChanged("libCodigo");
					this.OnlibCodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_libNombre", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string libNombre
		{
			get
			{
				return this._libNombre;
			}
			set
			{
				if ((this._libNombre != value))
				{
					this.OnlibNombreChanging(value);
					this.SendPropertyChanging();
					this._libNombre = value;
					this.SendPropertyChanged("libNombre");
					this.OnlibNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_libNumPag", DbType="Int NOT NULL")]
		public int libNumPag
		{
			get
			{
				return this._libNumPag;
			}
			set
			{
				if ((this._libNumPag != value))
				{
					this.OnlibNumPagChanging(value);
					this.SendPropertyChanging();
					this._libNumPag = value;
					this.SendPropertyChanged("libNumPag");
					this.OnlibNumPagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_libAutor", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string libAutor
		{
			get
			{
				return this._libAutor;
			}
			set
			{
				if ((this._libAutor != value))
				{
					this.OnlibAutorChanging(value);
					this.SendPropertyChanging();
					this._libAutor = value;
					this.SendPropertyChanged("libAutor");
					this.OnlibAutorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_libEditorial", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string libEditorial
		{
			get
			{
				return this._libEditorial;
			}
			set
			{
				if ((this._libEditorial != value))
				{
					this.OnlibEditorialChanging(value);
					this.SendPropertyChanging();
					this._libEditorial = value;
					this.SendPropertyChanged("libEditorial");
					this.OnlibEditorialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_areCodigo", DbType="Int NOT NULL")]
		public int areCodigo
		{
			get
			{
				return this._areCodigo;
			}
			set
			{
				if ((this._areCodigo != value))
				{
					if (this._Area.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnareCodigoChanging(value);
					this.SendPropertyChanging();
					this._areCodigo = value;
					this.SendPropertyChanged("areCodigo");
					this.OnareCodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Libro_DetallePrestamo", Storage="_DetallePrestamos", ThisKey="libCodigo", OtherKey="libCodigo")]
		public EntitySet<DetallePrestamo> DetallePrestamos
		{
			get
			{
				return this._DetallePrestamos;
			}
			set
			{
				this._DetallePrestamos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Area_Libro", Storage="_Area", ThisKey="areCodigo", OtherKey="areCodigo", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Area Area
		{
			get
			{
				return this._Area.Entity;
			}
			set
			{
				Area previousValue = this._Area.Entity;
				if (((previousValue != value) 
							|| (this._Area.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Area.Entity = null;
						previousValue.Libros.Remove(this);
					}
					this._Area.Entity = value;
					if ((value != null))
					{
						value.Libros.Add(this);
						this._areCodigo = value.areCodigo;
					}
					else
					{
						this._areCodigo = default(int);
					}
					this.SendPropertyChanged("Area");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DetallePrestamos(DetallePrestamo entity)
		{
			this.SendPropertyChanging();
			entity.Libro = this;
		}
		
		private void detach_DetallePrestamos(DetallePrestamo entity)
		{
			this.SendPropertyChanging();
			entity.Libro = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Prestamos")]
	public partial class Prestamo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _preCodigo;
		
		private System.DateTime _preFecha;
		
		private int _usuDocumento;
		
		private EntitySet<DetallePrestamo> _DetallePrestamos;
		
		private EntitySet<Sancione> _Sanciones;
		
		private EntityRef<Usuario> _Usuario;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnpreCodigoChanging(int value);
    partial void OnpreCodigoChanged();
    partial void OnpreFechaChanging(System.DateTime value);
    partial void OnpreFechaChanged();
    partial void OnusuDocumentoChanging(int value);
    partial void OnusuDocumentoChanged();
    #endregion
		
		public Prestamo()
		{
			this._DetallePrestamos = new EntitySet<DetallePrestamo>(new Action<DetallePrestamo>(this.attach_DetallePrestamos), new Action<DetallePrestamo>(this.detach_DetallePrestamos));
			this._Sanciones = new EntitySet<Sancione>(new Action<Sancione>(this.attach_Sanciones), new Action<Sancione>(this.detach_Sanciones));
			this._Usuario = default(EntityRef<Usuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_preCodigo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int preCodigo
		{
			get
			{
				return this._preCodigo;
			}
			set
			{
				if ((this._preCodigo != value))
				{
					this.OnpreCodigoChanging(value);
					this.SendPropertyChanging();
					this._preCodigo = value;
					this.SendPropertyChanged("preCodigo");
					this.OnpreCodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_preFecha", DbType="Date NOT NULL")]
		public System.DateTime preFecha
		{
			get
			{
				return this._preFecha;
			}
			set
			{
				if ((this._preFecha != value))
				{
					this.OnpreFechaChanging(value);
					this.SendPropertyChanging();
					this._preFecha = value;
					this.SendPropertyChanged("preFecha");
					this.OnpreFechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuDocumento", DbType="Int NOT NULL")]
		public int usuDocumento
		{
			get
			{
				return this._usuDocumento;
			}
			set
			{
				if ((this._usuDocumento != value))
				{
					if (this._Usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnusuDocumentoChanging(value);
					this.SendPropertyChanging();
					this._usuDocumento = value;
					this.SendPropertyChanged("usuDocumento");
					this.OnusuDocumentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Prestamo_DetallePrestamo", Storage="_DetallePrestamos", ThisKey="preCodigo", OtherKey="preCodigo")]
		public EntitySet<DetallePrestamo> DetallePrestamos
		{
			get
			{
				return this._DetallePrestamos;
			}
			set
			{
				this._DetallePrestamos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Prestamo_Sancione", Storage="_Sanciones", ThisKey="preCodigo", OtherKey="preCodigo")]
		public EntitySet<Sancione> Sanciones
		{
			get
			{
				return this._Sanciones;
			}
			set
			{
				this._Sanciones.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_Prestamo", Storage="_Usuario", ThisKey="usuDocumento", OtherKey="usuDocumento", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Usuario Usuario
		{
			get
			{
				return this._Usuario.Entity;
			}
			set
			{
				Usuario previousValue = this._Usuario.Entity;
				if (((previousValue != value) 
							|| (this._Usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Usuario.Entity = null;
						previousValue.Prestamos.Remove(this);
					}
					this._Usuario.Entity = value;
					if ((value != null))
					{
						value.Prestamos.Add(this);
						this._usuDocumento = value.usuDocumento;
					}
					else
					{
						this._usuDocumento = default(int);
					}
					this.SendPropertyChanged("Usuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DetallePrestamos(DetallePrestamo entity)
		{
			this.SendPropertyChanging();
			entity.Prestamo = this;
		}
		
		private void detach_DetallePrestamos(DetallePrestamo entity)
		{
			this.SendPropertyChanging();
			entity.Prestamo = null;
		}
		
		private void attach_Sanciones(Sancione entity)
		{
			this.SendPropertyChanging();
			entity.Prestamo = this;
		}
		
		private void detach_Sanciones(Sancione entity)
		{
			this.SendPropertyChanging();
			entity.Prestamo = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Sanciones")]
	public partial class Sancione : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _sanCodigo;
		
		private int _sanDiasSancion;
		
		private System.DateTime _sanFechaInicio;
		
		private System.DateTime _sanFechaFin;
		
		private int _preCodigo;
		
		private EntityRef<Prestamo> _Prestamo;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnsanCodigoChanging(int value);
    partial void OnsanCodigoChanged();
    partial void OnsanDiasSancionChanging(int value);
    partial void OnsanDiasSancionChanged();
    partial void OnsanFechaInicioChanging(System.DateTime value);
    partial void OnsanFechaInicioChanged();
    partial void OnsanFechaFinChanging(System.DateTime value);
    partial void OnsanFechaFinChanged();
    partial void OnpreCodigoChanging(int value);
    partial void OnpreCodigoChanged();
    #endregion
		
		public Sancione()
		{
			this._Prestamo = default(EntityRef<Prestamo>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sanCodigo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int sanCodigo
		{
			get
			{
				return this._sanCodigo;
			}
			set
			{
				if ((this._sanCodigo != value))
				{
					this.OnsanCodigoChanging(value);
					this.SendPropertyChanging();
					this._sanCodigo = value;
					this.SendPropertyChanged("sanCodigo");
					this.OnsanCodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sanDiasSancion", DbType="Int NOT NULL")]
		public int sanDiasSancion
		{
			get
			{
				return this._sanDiasSancion;
			}
			set
			{
				if ((this._sanDiasSancion != value))
				{
					this.OnsanDiasSancionChanging(value);
					this.SendPropertyChanging();
					this._sanDiasSancion = value;
					this.SendPropertyChanged("sanDiasSancion");
					this.OnsanDiasSancionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sanFechaInicio", DbType="Date NOT NULL")]
		public System.DateTime sanFechaInicio
		{
			get
			{
				return this._sanFechaInicio;
			}
			set
			{
				if ((this._sanFechaInicio != value))
				{
					this.OnsanFechaInicioChanging(value);
					this.SendPropertyChanging();
					this._sanFechaInicio = value;
					this.SendPropertyChanged("sanFechaInicio");
					this.OnsanFechaInicioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sanFechaFin", DbType="Date NOT NULL")]
		public System.DateTime sanFechaFin
		{
			get
			{
				return this._sanFechaFin;
			}
			set
			{
				if ((this._sanFechaFin != value))
				{
					this.OnsanFechaFinChanging(value);
					this.SendPropertyChanging();
					this._sanFechaFin = value;
					this.SendPropertyChanged("sanFechaFin");
					this.OnsanFechaFinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_preCodigo", DbType="Int NOT NULL")]
		public int preCodigo
		{
			get
			{
				return this._preCodigo;
			}
			set
			{
				if ((this._preCodigo != value))
				{
					if (this._Prestamo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnpreCodigoChanging(value);
					this.SendPropertyChanging();
					this._preCodigo = value;
					this.SendPropertyChanged("preCodigo");
					this.OnpreCodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Prestamo_Sancione", Storage="_Prestamo", ThisKey="preCodigo", OtherKey="preCodigo", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Prestamo Prestamo
		{
			get
			{
				return this._Prestamo.Entity;
			}
			set
			{
				Prestamo previousValue = this._Prestamo.Entity;
				if (((previousValue != value) 
							|| (this._Prestamo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Prestamo.Entity = null;
						previousValue.Sanciones.Remove(this);
					}
					this._Prestamo.Entity = value;
					if ((value != null))
					{
						value.Sanciones.Add(this);
						this._preCodigo = value.preCodigo;
					}
					else
					{
						this._preCodigo = default(int);
					}
					this.SendPropertyChanged("Prestamo");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
